### PR TITLE
Initial Commit .NET Standard 2.1 Version

### PR DESCRIPTION
**Pull request by SvenVandenbrande**

### CODE REVIEW

**Comment by loxone-mahriwo** [comment]
@SvenVandenbrande I just had quick look into the code. Unfortunate you are using a different coding style.
Naming Conventions very similar to the Naming Conventions that Microsoft provides for .Net developers. The name should describe the variable in a way so there is no comment needed. Don't use to much shortcuts of words.
Layout Conventions are a bit different. Opening curly braces don't get their own line and are always on the same line with the statements.
 Don't use implicit variable types for simple types (var). Only long complex generic types could be used so the length of the line does not blow up and gets unreadable.

**Comment by SvenVandenbrande** [comment]
@LxWolfgang ? 
It's almost the same code as in the development branch. It's for the most a copy paste from the development branch.
Only idd some formatting stuff that's done by my "CodeMaid" extension.

Where do you see the difference in code?

**Comment by loxone-mahriwo** [comment]
@SvenVandenbrande  Yes I mean the formatting. It is causing many code differences and also does not fit to our coding styles.
It makes it really hard to review your changes, because there are many unnecessary changes.

**Comment by davidwallis** [comment]
Is it worth adding stylecop to the project this would then stop things like this being an issue?

**Comment by SvenVandenbrande** [comment]
@davidwallis3101 Indeed. That would be a great idea

@LxWolfgang I just created a new project and copy pasted the code and did some minor changes. And saving my code activated my CodeMaid extension.
And I am also prefer this way of brackets, for readability. :) 

You indeed need some stylecop and/or analyzers if you need some checks. 
So if you can add this for the Loxone organization?
So the community knows what can and what not. We only want to help you guys.

**Comment by loxone-mahriwo** [comment]
@SvenVandenbrande, @davidwallis3101  I just added a .edithorconfig file to the development branch.
It contains all the coding style information for Visual Studio. Code refactoring will use this configuration.

**Comment by SvenVandenbrande** [comment]
@LxWolfgang I tried it, but I don't get it working on my machine :(

**Comment by loxone-mahriwo** [comment]
@SvenVandenbrande I didn't used the .edithorconfig feature before.
I've looked it up herer https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019.
Unfortunately at the moment I've no time to investigate this in detail, but I guess I may have time around the end of the week.

**Comment by SvenVandenbrande** [comment]
@LxWolfgang What's the status for this?

**Comment by loxone-mahriwo** [comment]
@SvenVandenbrande I will accept this request. But I will do make some changes myself before it will published.
I will changes the Project Settings to Target multiple frameworks.

**Pull request merged**
